// ============================================================================
// ISTAROTH GLOBAL & INDIA EVENTS PIPELINE DATABASE
// Hierarchical: World Hubs -> India National Pipeline -> Specific Indian Cities
// ============================================================================

export const PIPELINE_SOURCES = [
  { id: 'luma', name: 'Luma Protocol API', status: 'Healthy', icon: 'zap' },
  { id: 'devfolio', name: 'Devfolio India Ingestion', status: 'Healthy', icon: 'code' },
  { id: 'meetup', name: 'Global Tech Meetup Network', status: 'Healthy', icon: 'users' },
  { id: 'eventbrite', name: 'Eventbrite Enterprise Feed', status: 'Healthy', icon: 'ticket' },
  { id: 'unstop', name: 'Unstop Campus & Hackathon Pipeline', status: 'Healthy', icon: 'award' },
  { id: 'istaroth-native', name: 'Istaroth Direct Protocol Ingestion', status: 'Live', icon: 'sparkles' }
];

export const WORLD_REGIONS = [
  { id: 'all', name: 'All World & India', flag: '🌐', currency: 'USD', symbol: '$', category: 'world' },
  { id: 'india', name: 'All India (National Feed)', flag: '🇮🇳', currency: 'INR', symbol: '₹', category: 'india' },
  { id: 'sf', name: 'San Francisco & Bay Area', flag: '🇺🇸', currency: 'USD', symbol: '$', category: 'world', lat: 37.7749, lng: -122.4194 },
  { id: 'nyc', name: 'New York City', flag: '🇺🇸', currency: 'USD', symbol: '$', category: 'world', lat: 40.7128, lng: -74.0060 },
  { id: 'london', name: 'London', flag: '🇬🇧', currency: 'GBP', symbol: '£', category: 'world', lat: 51.5074, lng: -0.1278 },
  { id: 'berlin', name: 'Berlin', flag: '🇩🇪', currency: 'EUR', symbol: '€', category: 'world', lat: 52.5200, lng: 13.4050 },
  { id: 'tokyo', name: 'Tokyo', flag: '🇯🇵', currency: 'JPY', symbol: '¥', category: 'world', lat: 35.6762, lng: 139.6503 },
  { id: 'dubai', name: 'Dubai', flag: '🇦🇪', currency: 'AED', symbol: 'AED ', category: 'world', lat: 25.2048, lng: 55.2708 },
  { id: 'singapore', name: 'Singapore', flag: '🇸🇬', currency: 'SGD', symbol: 'S$', category: 'world', lat: 1.3521, lng: 103.8198 },
  { id: 'virtual', name: 'Global Virtual', flag: '⚡', currency: 'USD', symbol: '$', category: 'world' }
];

export const INDIA_CITIES = [
  { id: 'mumbai', name: 'Mumbai', state: 'Maharashtra', tag: 'FinTech Capital & MediaTech', landmark: 'Gateway of India', landmarkIcon: 'landmark', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 19.0760, lng: 72.8777, eventsCount: 3, isPopular: true },
  { id: 'delhi', name: 'Delhi NCR', state: 'Delhi / Gurugram / Noida', tag: 'AI Policy & FinTech', landmark: 'India Gate', landmarkIcon: 'flag', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 28.6139, lng: 77.2090, eventsCount: 3, isPopular: true },
  { id: 'bengaluru', name: 'Bengaluru', state: 'Karnataka', tag: 'Silicon Valley of India', landmark: 'Vidhana Soudha', landmarkIcon: 'cpu', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 12.9716, lng: 77.5946, eventsCount: 4, isPopular: true },
  { id: 'hyderabad', name: 'Hyderabad', state: 'Telangana', tag: 'Cyberabad & Cloud Hub', landmark: 'Charminar', landmarkIcon: 'castle', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 17.3850, lng: 78.4867, eventsCount: 3, isPopular: true },
  { id: 'ahmedabad', name: 'Ahmedabad', state: 'Gujarat', tag: 'GIFT City & Financial Hub', landmark: 'Atal Bridge', landmarkIcon: 'building-2', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 23.0225, lng: 72.5714, eventsCount: 2, isPopular: true },
  { id: 'chandigarh', name: 'Chandigarh', state: 'Punjab / Haryana', tag: 'Tri-City Tech Corridor', landmark: 'Open Hand Monument', landmarkIcon: 'trees', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 30.7333, lng: 76.7794, eventsCount: 1, isPopular: true },
  { id: 'chennai', name: 'Chennai', state: 'Tamil Nadu', tag: 'SaaS Corridor & DeepTech', landmark: 'Marina & Central', landmarkIcon: 'anchor', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 13.0827, lng: 80.2707, eventsCount: 2, isPopular: true },
  { id: 'pune', name: 'Pune', state: 'Maharashtra', tag: 'Open Source & DevCon', landmark: 'Shaniwar Wada', landmarkIcon: 'shield', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 18.5204, lng: 73.8567, eventsCount: 2, isPopular: true },
  { id: 'kolkata', name: 'Kolkata', state: 'West Bengal', tag: 'Data Science & Academia', landmark: 'Howrah Bridge', landmarkIcon: 'network', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 22.5726, lng: 88.3639, eventsCount: 2, isPopular: true },
  { id: 'kochi', name: 'Kochi', state: 'Kerala', tag: 'Maker Village & Tech Island', landmark: 'Chinese Nets', landmarkIcon: 'compass', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 9.9312, lng: 76.2673, eventsCount: 2, isPopular: true },
  { id: 'jaipur', name: 'Jaipur', state: 'Rajasthan', tag: 'Startups & Emerging Tech', landmark: 'Hawa Mahal', landmarkIcon: 'sun', flag: '🇮🇳', currency: 'INR', symbol: '₹', lat: 26.9124, lng: 75.7873, eventsCount: 1, isPopular: true }
];

export const CATEGORIES = [
  { id: 'all', name: 'All Categories', icon: 'sparkles' },
  { id: 'ai-tech', name: 'AI & Frontier Tech', icon: 'cpu' },
  { id: 'hackathon', name: 'Hackathons & Dev', icon: 'code' },
  { id: 'founders-vc', name: 'Founders & VC', icon: 'trending-up' },
  { id: 'design-creative', name: 'Design & Product', icon: 'palette' },
  { id: 'web3-crypto', name: 'Web3 & Decentralized', icon: 'boxes' },
  { id: 'music-culture', name: 'Tech & Music Afterhours', icon: 'music' }
];

export const INITIAL_EVENTS = [
  // ==================== INDIA: BENGALURU ====================
  {
    id: 'evt-in-blr-01',
    title: 'Bengaluru AI Founders & Agentic Scale Summit 2026',
    region: 'bengaluru',
    country: 'india',
    category: 'founders-vc',
    date: 'OCT 30, 2026',
    time: '09:00 AM - 06:30 PM IST',
    venue: 'Sheraton Grand, Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
    price: 2999,
    vipPrice: 7999,
    currency: 'INR',
    symbol: '₹',
    badge: 'Flagship Summit',
    organizer: 'India SaaS & AI Guild',
    pipelineSource: 'devfolio',
    verifiedOrganizer: true,
    totalCapacity: 850,
    ticketsSold: 710,
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1000&q=80',
    description: 'India’s largest gathering of tech founders, CTOs, and global VCs building foundational autonomous agents and enterprise SaaS from India for the world.',
    tags: ['Bengaluru', 'AI Startups', 'SaaS', 'VC Mixers']
  },
  {
    id: 'evt-in-blr-02',
    title: 'Koramangala 48h Fullstack & LLM Hackathon',
    region: 'bengaluru',
    country: 'india',
    category: 'hackathon',
    date: 'NOV 14-16, 2026',
    time: 'Starts 06:00 PM Fri',
    venue: 'Indiqube Tech Arena, Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    price: 499,
    vipPrice: 1499,
    currency: 'INR',
    symbol: '₹',
    badge: '₹10 Lakh Bounties',
    organizer: 'Bangalore Dev Circle',
    pipelineSource: 'devfolio',
    verifiedOrganizer: true,
    totalCapacity: 400,
    ticketsSold: 345,
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80',
    description: 'Hack with top engineering teams on high-throughput RAG, local SLMs, edge functions, and autonomous voice workflows.',
    tags: ['Hackathon', 'LLMs', 'Koramangala', 'Cash Prizes']
  },
  {
    id: 'evt-in-blr-03',
    title: 'HSR Layout Design Systems & Motion UI Lab',
    region: 'bengaluru',
    country: 'india',
    category: 'design-creative',
    date: 'NOV 22, 2026',
    time: '02:00 PM - 07:00 PM IST',
    venue: 'WeWork Galaxy, Residency Rd / HSR',
    city: 'Bengaluru',
    state: 'Karnataka',
    price: 999,
    vipPrice: 2499,
    currency: 'INR',
    symbol: '₹',
    badge: 'Design Craft',
    organizer: 'Figma India Community',
    pipelineSource: 'meetup',
    verifiedOrganizer: true,
    totalCapacity: 250,
    ticketsSold: 215,
    image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1000&q=80',
    description: 'Hands-on architectural masterclasses on design tokens, micro-animations, Figma variables, and accessible frontend systems.',
    tags: ['Design', 'UI/UX', 'Figma', 'Frontend']
  },

  // ==================== INDIA: HYDERABAD ====================
  {
    id: 'evt-in-hyd-01',
    title: 'HITEC City Generative Cloud & Data Conclave',
    region: 'hyderabad',
    country: 'india',
    category: 'ai-tech',
    date: 'NOV 08, 2026',
    time: '09:30 AM - 05:30 PM IST',
    venue: 'HICC Novotel, HITEC City',
    city: 'Hyderabad',
    state: 'Telangana',
    price: 1999,
    vipPrice: 4999,
    currency: 'INR',
    symbol: '₹',
    badge: 'Enterprise AI',
    organizer: 'Telangana Innovation Cloud',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 600,
    ticketsSold: 512,
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1000&q=80',
    description: 'Deep dives into scalable GPU clusters, distributed vector databases, enterprise security in LLMs, and multi-cloud architectures.',
    tags: ['Hyderabad', 'Cloud', 'Data Infrastructure', 'Enterprise']
  },
  {
    id: 'evt-in-hyd-02',
    title: 'T-Hub Hardware & Robotics Builders Showcase',
    region: 'hyderabad',
    country: 'india',
    category: 'ai-tech',
    date: 'NOV 28, 2026',
    time: '10:00 AM - 06:00 PM IST',
    venue: 'T-Hub Phase 2, Knowledge City',
    city: 'Hyderabad',
    state: 'Telangana',
    price: 799,
    vipPrice: 1999,
    currency: 'INR',
    symbol: '₹',
    badge: 'Hardware & IoT',
    organizer: 'T-Hub Robotics Circle',
    pipelineSource: 'devfolio',
    verifiedOrganizer: true,
    totalCapacity: 350,
    ticketsSold: 280,
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1000&q=80',
    description: 'Showcasing drone autonomy, edge AI accelerators, medical robotics, and industrial IoT solutions built in India.',
    tags: ['T-Hub', 'Robotics', 'Hardware', 'Sensors']
  },

  // ==================== INDIA: DELHI NCR ====================
  {
    id: 'evt-in-del-01',
    title: 'Delhi NCR FinTech & Sovereign AI Forum',
    region: 'delhi',
    country: 'india',
    category: 'founders-vc',
    date: 'NOV 12, 2026',
    time: '09:00 AM - 06:00 PM IST',
    venue: 'Bharat Mandapam, Pragati Maidan',
    city: 'Delhi NCR',
    state: 'Delhi',
    price: 3499,
    vipPrice: 8999,
    currency: 'INR',
    symbol: '₹',
    badge: 'Government & VC',
    organizer: 'India Tech Council & FinTech Guild',
    pipelineSource: 'eventbrite',
    verifiedOrganizer: true,
    totalCapacity: 900,
    ticketsSold: 780,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1000&q=80',
    description: 'Connecting regulatory leaders, fintech unicorns, and AI researchers to discuss national digital public infrastructure and financial AI.',
    tags: ['Delhi', 'Fintech', 'Sovereign AI', 'Policy']
  },
  {
    id: 'evt-in-del-02',
    title: 'Gurugram Zero-to-One Founder Mixer & Pitch Arena',
    region: 'delhi',
    country: 'india',
    category: 'founders-vc',
    date: 'DEC 02, 2026',
    time: '06:00 PM - 10:00 PM IST',
    venue: 'Cyber Hub Arena, DLF CyberCity, Gurugram',
    city: 'Delhi NCR',
    state: 'Haryana',
    price: 1200,
    vipPrice: 2800,
    currency: 'INR',
    symbol: '₹',
    badge: 'Angel & VC',
    organizer: 'North India Ventures',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 300,
    ticketsSold: 260,
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=80',
    description: 'Curated networking evening with active tier-1 angels and seed funds investing in AI, D2C, and B2B software.',
    tags: ['Gurugram', 'CyberHub', 'Venture Capital', 'Pitch']
  },

  // ==================== INDIA: MUMBAI ====================
  {
    id: 'evt-in-mum-01',
    title: 'Mumbai BKC Algorithmic & Web3 Finance Conclave',
    region: 'mumbai',
    country: 'india',
    category: 'web3-crypto',
    date: 'NOV 18, 2026',
    time: '10:00 AM - 06:00 PM IST',
    venue: 'Jio World Convention Centre, BKC',
    city: 'Mumbai',
    state: 'Maharashtra',
    price: 3999,
    vipPrice: 9999,
    currency: 'INR',
    symbol: '₹',
    badge: 'Executive',
    organizer: 'Bombay FinTech Alliance',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 750,
    ticketsSold: 640,
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1000&q=80',
    description: 'High-frequency algorithmic systems, tokenized real-world assets (RWA), central bank digital currencies, and institutional Web3 rails.',
    tags: ['Mumbai', 'BKC', 'Fintech', 'Quant']
  },
  {
    id: 'evt-in-mum-02',
    title: 'Bandra Generative Media & Visual FX Summit',
    region: 'mumbai',
    country: 'india',
    category: 'design-creative',
    date: 'DEC 05, 2026',
    time: '01:00 PM - 09:00 PM IST',
    venue: 'Mehboob Studios, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    price: 1800,
    vipPrice: 4200,
    currency: 'INR',
    symbol: '₹',
    badge: 'Media & Cinema',
    organizer: 'Bollywood & AI Creators Network',
    pipelineSource: 'unstop',
    verifiedOrganizer: true,
    totalCapacity: 500,
    ticketsSold: 430,
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1000&q=80',
    description: 'AI visual generation, virtual production LED stages, motion synthesis, and the future of Indian cinema technology.',
    tags: ['Bandra', 'MediaTech', 'Visual FX', 'Generative Art']
  },

  // ==================== INDIA: PUNE ====================
  {
    id: 'evt-in-pun-01',
    title: 'Pune Open Source & Cloud-Native Con 2026',
    region: 'pune',
    country: 'india',
    category: 'hackathon',
    date: 'NOV 25, 2026',
    time: '09:30 AM - 05:30 PM IST',
    venue: 'JW Marriott Pune, Senapati Bapat Rd',
    city: 'Pune',
    state: 'Maharashtra',
    price: 1199,
    vipPrice: 2899,
    currency: 'INR',
    symbol: '₹',
    badge: 'DevCon',
    organizer: 'Pune Tech Community (PTC)',
    pipelineSource: 'meetup',
    verifiedOrganizer: true,
    totalCapacity: 450,
    ticketsSold: 390,
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80',
    description: 'Hands-on architectural breakdowns of Kubernetes at scale, Rust systems, observability pipelines, and distributed databases.',
    tags: ['Pune', 'Open Source', 'Kubernetes', 'Rust']
  },

  // ==================== INDIA: CHENNAI ====================
  {
    id: 'evt-in-chn-01',
    title: 'Chennai OMR SaaS & DeepTech Assembly',
    region: 'chennai',
    country: 'india',
    category: 'founders-vc',
    date: 'DEC 01, 2026',
    time: '09:00 AM - 05:30 PM IST',
    venue: 'IIT Madras Research Park, Taramani',
    city: 'Chennai',
    state: 'Tamil Nadu',
    price: 1500,
    vipPrice: 3800,
    currency: 'INR',
    symbol: '₹',
    badge: 'DeepTech',
    organizer: 'SaasBOOMi & IIT Madras Incubator',
    pipelineSource: 'devfolio',
    verifiedOrganizer: true,
    totalCapacity: 500,
    ticketsSold: 420,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
    description: 'Where global SaaS leaders and deeptech researchers meet. Masterclasses on PLG, product engineering, quantum algorithms, and battery tech.',
    tags: ['Chennai', 'OMR', 'IIT Madras', 'SaaS']
  },

  // ==================== INDIA: AHMEDABAD / GIFT CITY ====================
  {
    id: 'evt-in-ahm-01',
    title: 'GIFT City International FinTech & Tokenomics Summit',
    region: 'ahmedabad',
    country: 'india',
    category: 'web3-crypto',
    date: 'DEC 09, 2026',
    time: '10:00 AM - 06:00 PM IST',
    venue: 'GIFT International Club, Gandhinagar',
    city: 'Ahmedabad / GIFT City',
    state: 'Gujarat',
    price: 2500,
    vipPrice: 6000,
    currency: 'INR',
    symbol: '₹',
    badge: 'International Zone',
    organizer: 'GIFT City Innovation Authority',
    pipelineSource: 'eventbrite',
    verifiedOrganizer: true,
    totalCapacity: 400,
    ticketsSold: 320,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80',
    description: 'Cross-border payment infrastructure, digital bullion, algorithmic clearinghouses, and IFSC regulatory sandbox insights.',
    tags: ['GIFT City', 'Ahmedabad', 'IFSC', 'Tokenomics']
  },

  // ==================== INDIA: KOCHI ====================
  {
    id: 'evt-in-koc-01',
    title: 'Kochi Maker Village IoT & Edge Computing Hack',
    region: 'kochi',
    country: 'india',
    category: 'hackathon',
    date: 'DEC 12-14, 2026',
    time: '48h Hardware Sprint',
    venue: 'Maker Village, Kinfra Hi-Tech Park, Kalamassery',
    city: 'Kochi',
    state: 'Kerala',
    price: 499,
    vipPrice: 1299,
    currency: 'INR',
    symbol: '₹',
    badge: 'Hardware Hack',
    organizer: 'Kerala Startup Mission',
    pipelineSource: 'unstop',
    verifiedOrganizer: true,
    totalCapacity: 250,
    ticketsSold: 210,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80',
    description: 'Hardware hacking with rapid prototyping kits, sensor fusion, drone telemetry, and marine tech innovations.',
    tags: ['Kochi', 'Maker Village', 'Hardware', 'Kerala']
  },

  // ==================== INDIA: KOLKATA ====================
  {
    id: 'evt-in-kol-01',
    title: 'Kolkata Sector V Data Science & ML Colloquium',
    region: 'kolkata',
    country: 'india',
    category: 'ai-tech',
    date: 'DEC 16, 2026',
    time: '10:00 AM - 05:00 PM IST',
    venue: 'Biswa Bangla Convention Centre, New Town',
    city: 'Kolkata',
    state: 'West Bengal',
    price: 899,
    vipPrice: 2199,
    currency: 'INR',
    symbol: '₹',
    badge: 'Academic & AI',
    organizer: 'ISI & Kolkata AI Collective',
    pipelineSource: 'meetup',
    verifiedOrganizer: true,
    totalCapacity: 400,
    ticketsSold: 330,
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&q=80',
    description: 'Statistical machine learning, bioinformatics pipelines, causal inference, and neural algorithmic reasoning.',
    tags: ['Kolkata', 'Data Science', 'Machine Learning', 'ISI']
  },

  // ==================== WORLD HUBS ====================
  // SAN FRANCISCO
  {
    id: 'evt-sf-01',
    title: 'Autonomous Agents World Summit 2026',
    region: 'sf',
    country: 'usa',
    category: 'ai-tech',
    date: 'OCT 14, 2026',
    time: '09:00 AM - 06:00 PM PST',
    venue: 'Yerba Buena Center for the Arts',
    city: 'San Francisco, CA',
    price: 199,
    vipPrice: 499,
    currency: 'USD',
    symbol: '$',
    badge: 'Global Flagship',
    organizer: 'NextGen AI Collective',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 600,
    ticketsSold: 482,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=80',
    description: 'The premier gathering of AI researchers, foundation model builders, and autonomous agent engineers. Live multi-agent demonstrations and developer keynotes.',
    tags: ['Autonomous AI', 'LLMs', 'San Francisco', 'Keynotes']
  },

  // NEW YORK
  {
    id: 'evt-nyc-01',
    title: 'Manhattan AI & Quant Finance Forum',
    region: 'nyc',
    country: 'usa',
    category: 'founders-vc',
    date: 'NOV 05, 2026',
    time: '10:00 AM - 05:00 PM EST',
    venue: 'Spring Studios, Tribeca',
    city: 'New York, NY',
    price: 249,
    vipPrice: 650,
    currency: 'USD',
    symbol: '$',
    badge: 'Executive',
    organizer: 'Wall Street Tech Alliance',
    pipelineSource: 'eventbrite',
    verifiedOrganizer: true,
    totalCapacity: 450,
    ticketsSold: 390,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80',
    description: 'Where algorithmic hedge funds meet cutting-edge deep learning. Panel discussions on high-frequency trading models and alternative data pipelines.',
    tags: ['Fintech', 'Quant', 'Venture Capital', 'NYC']
  },

  // LONDON
  {
    id: 'evt-lon-01',
    title: 'London DeepTech & Quantum Symposium',
    region: 'london',
    country: 'uk',
    category: 'ai-tech',
    date: 'OCT 18, 2026',
    time: '09:30 AM - 05:30 PM BST',
    venue: 'The Barbican Centre',
    city: 'London, UK',
    price: 180,
    vipPrice: 420,
    currency: 'GBP',
    symbol: '£',
    badge: 'Keynote',
    organizer: 'Imperial & UCL Tech Network',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 500,
    ticketsSold: 410,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1000&q=80',
    description: 'Europe’s leading engineers discussing superconducting quantum processors, bio-computing, and hardware acceleration.',
    tags: ['DeepTech', 'Quantum', 'London', 'Science']
  },

  // BERLIN
  {
    id: 'evt-ber-01',
    title: 'Berlin Open Source & Rust Conf 2026',
    region: 'berlin',
    country: 'germany',
    category: 'hackathon',
    date: 'NOV 20, 2026',
    time: '10:00 AM - 06:00 PM CET',
    venue: 'Kulturbrauerei, Prenzlauer Berg',
    city: 'Berlin, Germany',
    price: 110,
    vipPrice: 240,
    currency: 'EUR',
    symbol: '€',
    badge: 'Engineering',
    organizer: 'EuroRust Community',
    pipelineSource: 'meetup',
    verifiedOrganizer: true,
    totalCapacity: 400,
    ticketsSold: 345,
    image: 'https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?auto=format&fit=crop&w=1000&q=80',
    description: 'Deep dives into systems programming, memory safety, WASM runtimes, and high-throughput networking in Rust.',
    tags: ['Rust', 'Open Source', 'Systems', 'Berlin']
  },

  // TOKYO
  {
    id: 'evt-tok-01',
    title: 'Tokyo Robotics & Humanoid AI Expo',
    region: 'tokyo',
    country: 'japan',
    category: 'ai-tech',
    date: 'NOV 27, 2026',
    time: '10:00 AM - 06:00 PM JST',
    venue: 'Tokyo Big Sight, Odaiba',
    city: 'Tokyo, Japan',
    price: 12000,
    vipPrice: 35000,
    currency: 'JPY',
    symbol: '¥',
    badge: 'Futuristic',
    organizer: 'Nippon Robotics Institute',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 1200,
    ticketsSold: 980,
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80',
    description: 'Experience next-generation bipedal robots, computer vision actuators, tactile sensors, and humanoid robotics operating in real-world spaces.',
    tags: ['Robotics', 'Hardware', 'Tokyo', 'Sensors']
  },

  // DUBAI
  {
    id: 'evt-dxb-01',
    title: 'Dubai Global Web3 & Sovereign AI Congress',
    region: 'dubai',
    country: 'uae',
    category: 'web3-crypto',
    date: 'DEC 04, 2026',
    time: '09:00 AM - 06:00 PM GST',
    venue: 'Museum of the Future / Emirates Towers',
    city: 'Dubai, UAE',
    price: 450,
    vipPrice: 1200,
    currency: 'AED',
    symbol: 'AED ',
    badge: 'Premier',
    organizer: 'Gulf Future Innovation Council',
    pipelineSource: 'luma',
    verifiedOrganizer: true,
    totalCapacity: 800,
    ticketsSold: 710,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=80',
    description: 'Sovereign wealth funds, protocol architects, and researchers discussing decentralized computing clusters, regulatory frameworks, and tokenomics.',
    tags: ['Web3', 'Sovereign AI', 'Dubai', 'Fintech']
  }
];

export const INITIAL_LEDGER = [
  {
    id: 'TXN-9025',
    eventTitle: 'Bengaluru AI Founders & Agentic Scale Summit 2026',
    buyerName: 'Vikramaditya Roy',
    buyerEmail: 'vikram@neuralindia.ai',
    tier: 'VIP Pass',
    quantity: 1,
    subtotal: 7999.00,
    platformRate: 0.08,
    platformFeeCut: 639.92,
    organizerPayout: 7359.08,
    timestamp: '2026-09-30 01:15',
    region: 'bengaluru',
    currency: '₹'
  },
  {
    id: 'TXN-9024',
    eventTitle: 'HITEC City Generative Cloud & Data Conclave',
    buyerName: 'Sneha Reddy',
    buyerEmail: 'sneha.reddy@cloudscale.in',
    tier: 'General Pass',
    quantity: 2,
    subtotal: 3998.00,
    platformRate: 0.08,
    platformFeeCut: 319.84,
    organizerPayout: 3678.16,
    timestamp: '2026-09-30 00:48',
    region: 'hyderabad',
    currency: '₹'
  },
  {
    id: 'TXN-9023',
    eventTitle: 'Mumbai BKC Algorithmic & Web3 Finance Conclave',
    buyerName: 'Rohan Shroff',
    buyerEmail: 'rohan@apexquant.mumbai',
    tier: 'General Pass',
    quantity: 1,
    subtotal: 3999.00,
    platformRate: 0.08,
    platformFeeCut: 319.92,
    organizerPayout: 3679.08,
    timestamp: '2026-09-29 23:30',
    region: 'mumbai',
    currency: '₹'
  },
  {
    id: 'TXN-9022',
    eventTitle: 'Autonomous Agents World Summit 2026',
    buyerName: 'Elena Rostova',
    buyerEmail: 'elena@frontiertech.io',
    tier: 'VIP Pass',
    quantity: 1,
    subtotal: 499.00,
    platformRate: 0.08,
    platformFeeCut: 39.92,
    organizerPayout: 459.08,
    timestamp: '2026-09-29 20:14',
    region: 'sf',
    currency: '$'
  },
  {
    id: 'TXN-9021',
    eventTitle: 'Delhi NCR FinTech & Sovereign AI Forum',
    buyerName: 'Aman Singhania',
    buyerEmail: 'aman@capitalpay.in',
    tier: 'General Pass',
    quantity: 2,
    subtotal: 6998.00,
    platformRate: 0.08,
    platformFeeCut: 559.84,
    organizerPayout: 6438.16,
    timestamp: '2026-09-29 18:05',
    region: 'delhi',
    currency: '₹'
  }
];

// ============================================================================
// DISTRICT BY ISTAROTH: DINING, MOVIES & SCREENINGS, AND COMEDY VERTICALS
// ============================================================================

export const DISTRICT_TABS = [
  { id: 'for_you', label: 'For you', icon: 'sparkles', badge: 'Curated' },
  { id: 'events', label: 'Events', icon: 'ticket', badge: 'Live' },
  { id: 'dining', label: 'Dining', icon: 'utensils', badge: 'Perks' },
  { id: 'movies', label: 'Movies', icon: 'film', badge: 'Now Showing' },
  { id: 'comedy', label: 'Comedy', icon: 'smile', badge: 'Gigs' }
];

export const FEATURED_HERO_CAROUSEL = [
  {
    id: 'hero-blr-summit',
    type: 'events',
    title: 'Bengaluru AI Founders & Agentic Scale Summit 2026',
    subtitle: 'Sheraton Grand Whitefield • 850 Founders & Global VCs',
    date: 'OCT 30, 2026',
    time: '09:00 AM IST',
    price: 2999,
    badge: '⚡ FAST FILLING',
    bgGradient: 'linear-gradient(135deg, #1E1B4B 0%, #312E81 50%, #4338CA 100%)',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    targetEventId: 'evt-in-blr-01'
  },
  {
    id: 'hero-dining-mixer',
    type: 'dining',
    title: 'Toit Brewpub & Rooftop: Sovereign AI VIP Mixer',
    subtitle: 'Indiranagar 100ft Rd • Reserved Builder Tables & Craft Ales',
    date: 'EVERY FRIDAY',
    time: '07:30 PM ONWARDS',
    price: 1800,
    badge: '🍽️ ISTAROTH PERK: 15% OFF',
    bgGradient: 'linear-gradient(135deg, #2A0845 0%, #6441A5 100%)',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
    targetDiningId: 'dine-blr-01'
  },
  {
    id: 'hero-movie-premiere',
    type: 'movies',
    title: 'Silicon Frontier: The Autonomous OS Documentary',
    subtitle: 'PVR INOX Director’s Cut, Forum Mall • IMAX 4K Laser',
    date: 'NOW SCREENING',
    time: '4 Shows Daily',
    price: 450,
    badge: '🎬 EXCLUSIVE PREMIERE',
    bgGradient: 'linear-gradient(135deg, #09203F 0%, #537895 100%)',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    targetMovieId: 'mov-01'
  },
  {
    id: 'hero-comedy-roast',
    type: 'comedy',
    title: 'Pitch Deck & Tech Debt Live Roast Show',
    subtitle: 'The Comedy Club, Koramangala • Featuring Standup Stars',
    date: 'NOV 08, 2026',
    time: '08:00 PM IST',
    price: 799,
    badge: '🎙️ VIRAL COMEDY SPECIAL',
    bgGradient: 'linear-gradient(135deg, #4A0E4E 0%, #89216B 100%)',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=1200&q=80',
    targetComedyId: 'cmd-01'
  }
];

export const DINING_VENUES = [
  // BENGALURU
  {
    id: 'dine-blr-01',
    name: 'Toit Brewpub & Rooftop',
    region: 'bengaluru',
    city: 'Bengaluru',
    neighborhood: 'Indiranagar 100ft Road',
    cuisine: 'Craft Microbrewery, Continental, Artisan Pizzas',
    rating: 4.8,
    reviewsCount: 3420,
    priceForTwo: 1800,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    perk: 'Flat 15% off with Istaroth Pass',
    tags: ['Tech Mixer Favorite', 'Outdoor Seating', 'Live Craft Beer'],
    features: ['Valet Parking', 'High-Speed Wi-Fi', 'Builder Friendly'],
    slots: ['01:00 PM', '07:30 PM', '09:00 PM', '10:30 PM']
  },
  {
    id: 'dine-blr-02',
    name: 'Windmills Craftworks & Jazz Lounge',
    region: 'bengaluru',
    city: 'Bengaluru',
    neighborhood: 'Whitefield Tech Corridor',
    cuisine: 'Modern Indian, Steakhouse, Gourmet Hops',
    rating: 4.9,
    reviewsCount: 2190,
    priceForTwo: 2800,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    perk: 'Complimentary Brewer Sampler with Istaroth Pass',
    tags: ['Founder Dinners', 'Jazz Stage', 'Quiet Meeting Alcoves'],
    features: ['Book Library', 'Acoustic Soundproofing', 'Private Dining'],
    slots: ['12:30 PM', '07:00 PM', '08:45 PM', '10:15 PM']
  },
  {
    id: 'dine-blr-03',
    name: 'The Fatty Bao Rooftop Asian Gastrobar',
    region: 'bengaluru',
    city: 'Bengaluru',
    neighborhood: 'Indiranagar 12th Main',
    cuisine: 'Pan-Asian, Baos, Ramen, Craft Cocktails',
    rating: 4.7,
    reviewsCount: 1840,
    priceForTwo: 2200,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80',
    perk: 'Pay & Split with Istaroth: 10% Cash Credit',
    tags: ['Rooftop View', 'Cocktail Lounge', 'Vibrant Vibe'],
    features: ['Cocktail Bar', 'Outdoor Skyline View'],
    slots: ['01:00 PM', '08:00 PM', '09:30 PM']
  },

  // HYDERABAD
  {
    id: 'dine-hyd-01',
    name: 'Prost Brewpub & Sky Terrace',
    region: 'hyderabad',
    city: 'Hyderabad',
    neighborhood: 'Jubilee Hills Road 45',
    cuisine: 'European, Handcrafted Ales, Tapas',
    rating: 4.8,
    reviewsCount: 2980,
    priceForTwo: 2200,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    perk: 'Istaroth Reserved Builder Table + 15% Off',
    tags: ['Jubilee Hills Skyline', 'Tech Founders Spot', 'Craft Beers'],
    features: ['Valet', 'Terrace Seating', 'Live DJ Night'],
    slots: ['01:00 PM', '07:30 PM', '09:15 PM', '11:00 PM']
  },
  {
    id: 'dine-hyd-02',
    name: 'Farzi Cafe Cyberabad',
    region: 'hyderabad',
    city: 'Hyderabad',
    neighborhood: 'Hitec City, Cyber Towers',
    cuisine: 'Modern Indian Molecular Gastronomy',
    rating: 4.6,
    reviewsCount: 2150,
    priceForTwo: 2000,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    perk: 'Free Chef Degustation Appetizer via Istaroth',
    tags: ['Cyberabad Hub', 'Business Lunches', 'Cocktail Laboratory'],
    features: ['Corporate Private Lounges', 'Fast Table Turnaround'],
    slots: ['12:30 PM', '01:30 PM', '08:00 PM', '09:30 PM']
  },

  // MUMBAI
  {
    id: 'dine-mum-01',
    name: 'Bastian BKC',
    region: 'mumbai',
    city: 'Mumbai',
    neighborhood: 'Bandra Kurla Complex (BKC)',
    cuisine: 'Seafood, Asian Contemporary, Artisanal Desserts',
    rating: 4.9,
    reviewsCount: 4100,
    priceForTwo: 3500,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80',
    perk: 'Istaroth VIP Priority Seating with No Waitlist',
    tags: ['BKC FinTech Elite', 'Celebrity Chef', 'High Energy'],
    features: ['Valet', 'VIP Lounge', 'Sommelier Selection'],
    slots: ['01:00 PM', '08:00 PM', '10:00 PM']
  },

  // DELHI NCR
  {
    id: 'dine-del-01',
    name: 'The Piano Man Jazz Club & Dining',
    region: 'delhi',
    city: 'Delhi NCR',
    neighborhood: 'Safdarjung Enclave & Gurugram',
    cuisine: 'European, Woodfired Platters, Signature Spirits',
    rating: 4.8,
    reviewsCount: 3890,
    priceForTwo: 2400,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80',
    perk: 'Reserved Stage-Facing Booth with Istaroth Pass',
    tags: ['Live Music', 'Artisan Kitchen', 'Delhi NCR Landmark'],
    features: ['Live Jazz Stage', 'Pre-Show Dinner Seating'],
    slots: ['07:00 PM', '08:30 PM', '10:00 PM']
  },

  // PUNE
  {
    id: 'dine-pune-01',
    name: 'Effingut Brewhouse & Terrace',
    region: 'pune',
    city: 'Pune',
    neighborhood: 'Koregaon Park',
    cuisine: 'Smoked Meats, Heifer Weizen, Artisan Burgers',
    rating: 4.7,
    reviewsCount: 2210,
    priceForTwo: 1700,
    currency: '₹',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    perk: '15% Off Food Bill for Istaroth Members',
    tags: ['Koregaon Park', 'Dev Community Meet', 'Fresh Brews'],
    features: ['Outdoor Beer Garden', 'Games & Pub Trivia'],
    slots: ['01:00 PM', '07:30 PM', '09:30 PM']
  }
];

export const MOVIES_SCREENINGS = [
  {
    id: 'mov-01',
    title: 'Silicon Frontier: The Autonomous OS Documentary',
    genre: 'Documentary • Technology • Startups',
    languages: 'English (Subtitles in Hindi/Japanese)',
    duration: '1h 54m',
    rating: '9.4/10 IMDb',
    status: 'Now Showing',
    badge: 'Istaroth Premiere',
    banner: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    description: 'An exclusive cinematic deep-dive behind the closed doors of research labs in San Francisco, Bengaluru, and Tokyo racing to deploy true agentic cognition.',
    cinemas: [
      {
        name: 'PVR INOX Director’s Cut, Forum Mall',
        neighborhood: 'Koramangala, Bengaluru',
        format: 'IMAX 4K Laser & Dolby Atmos',
        showtimes: ['10:45 AM', '02:15 PM', '06:30 PM', '09:45 PM'],
        price: 450
      },
      {
        name: 'Cinepolis Lulu Mall & Tech Arena',
        neighborhood: 'Rajajinagar, Bengaluru',
        format: 'VIP Recliner • 4K Digital',
        showtimes: ['11:30 AM', '04:00 PM', '08:15 PM'],
        price: 380
      },
      {
        name: 'PVR Next Galleria, Hitec City',
        neighborhood: 'Cyberabad, Hyderabad',
        format: '4K Dolby 7.1',
        showtimes: ['01:15 PM', '05:45 PM', '09:00 PM'],
        price: 350
      },
      {
        name: 'PVR Maison INOX, Jio World Drive, BKC',
        neighborhood: 'Bandra Kurla Complex, Mumbai',
        format: 'IMAX Enhanced Luxury',
        showtimes: ['12:00 PM', '04:30 PM', '08:45 PM'],
        price: 550
      }
    ]
  },
  {
    id: 'mov-02',
    title: 'The Open Source Paradox: Linux to LLMs',
    genre: 'Drama • History • Cyberculture',
    languages: 'English',
    duration: '2h 10m',
    rating: '9.1/10 IMDb',
    status: 'Now Showing',
    badge: 'Critically Acclaimed',
    banner: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    description: 'From 1991 kernel mailing lists to the 2026 decentralized AI wars: how rogue hackers and volunteer maintainers keep the global digital backbone alive.',
    cinemas: [
      {
        name: 'PVR Vega City IMAX, Bannerghatta',
        neighborhood: 'South Bengaluru',
        format: 'IMAX Laser 3D',
        showtimes: ['11:00 AM', '03:30 PM', '07:15 PM'],
        price: 400
      },
      {
        name: 'AMB Cinemas, Gachibowli',
        neighborhood: 'Gachibowli, Hyderabad',
        format: 'SuperScreen 4K Atmos',
        showtimes: ['02:00 PM', '06:00 PM', '09:30 PM'],
        price: 350
      },
      {
        name: 'PVR Priya, Vasant Vihar',
        neighborhood: 'South Delhi, Delhi NCR',
        format: 'Dolby Cinema',
        showtimes: ['01:30 PM', '06:45 PM', '10:00 PM'],
        price: 420
      }
    ]
  },
  {
    id: 'mov-03',
    title: 'AlphaGo & The Second Renaissance',
    genre: 'Documentary • Science • DeepMind',
    languages: 'English',
    duration: '1h 38m',
    rating: '9.6/10 IMDb',
    status: 'Special Anniversary Screening',
    badge: '10th Year Retrospective',
    banner: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    description: 'The remastered, unreleased extended cut documenting Move 37, featuring exclusive interviews with Demis Hassabis and the DeepMind frontier team.',
    cinemas: [
      {
        name: 'Indiranagar Film Club & Auditorium',
        neighborhood: 'Indiranagar, Bengaluru',
        format: '4K Projection & Panel Q&A',
        showtimes: ['05:00 PM', '08:30 PM'],
        price: 300
      },
      {
        name: 'Inox GVK One, Banjara Hills',
        neighborhood: 'Banjara Hills, Hyderabad',
        format: 'Inox Insignia',
        showtimes: ['04:00 PM', '07:45 PM'],
        price: 400
      }
    ]
  }
];

export const COMEDY_GIGS = [
  {
    id: 'cmd-01',
    title: 'Pitch Deck & Tech Debt: The Live Roast Show',
    artist: 'Rahul Dua & Friends (with Guest Founders)',
    city: 'Bengaluru',
    neighborhood: 'The Comedy Club, Koramangala',
    date: 'NOV 08, 2026',
    time: '08:00 PM IST',
    duration: '90 Mins',
    price: 799,
    vipPrice: 1799,
    currency: '₹',
    badge: 'Selling Fast',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=800&q=80',
    description: 'Real founders submit their seed pitch decks and cringiest LinkedIn influencer posts to be roasted live on stage with brutal comic timing.',
    tags: ['Roast Comedy', 'Founder Culture', 'Koramangala Gigs'],
    venue: 'The Humming Tree & Comedy Club, Koramangala'
  },
  {
    id: 'cmd-02',
    title: 'Standup Special: "Why My SLM Hallucinated"',
    artist: 'Kanan Gill Live Special',
    city: 'Bengaluru',
    neighborhood: 'Chowdiah Memorial Hall, Malleshwaram',
    date: 'NOV 21, 2026',
    time: '07:30 PM IST',
    duration: '105 Mins',
    price: 999,
    vipPrice: 2499,
    currency: '₹',
    badge: 'Tour Finale',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    description: 'An all-new national tour set covering 30-something tech anxieties, startup valuations, living in Bangalore traffic, and conversational AI chatbots.',
    tags: ['Solo Special', 'Bangalore Jokes', 'Live Recording'],
    venue: 'Chowdiah Memorial Hall, Bengaluru'
  },
  {
    id: 'cmd-03',
    title: 'Cyberabad Standup Jam: Hitec City Edition',
    artist: 'Anubhav Singh Bassi & Hyderabad Comedians',
    city: 'Hyderabad',
    neighborhood: 'Shilpakala Vedika, Hitec City',
    date: 'NOV 15, 2026',
    time: '06:30 PM IST',
    duration: '120 Mins',
    price: 899,
    vipPrice: 2199,
    currency: '₹',
    badge: 'Over 80% Booked',
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80',
    description: 'Hyderabad’s biggest auditorium comedy night bringing high energy, hilarious college nostalgia, corporate appraisal humor, and crowd interactions.',
    tags: ['Auditorium Show', 'Cyberabad', 'Hindi / English Comedy'],
    venue: 'Shilpakala Vedika Auditorium, Hitec City'
  },
  {
    id: 'cmd-04',
    title: 'Mumbai Standup & Roast: Bandra Underground',
    artist: 'Samay Raina & Tanmay Bhat Afterhours',
    city: 'Mumbai',
    neighborhood: 'Bal Gandharva Rang Mandir, Bandra West',
    date: 'NOV 28, 2026',
    time: '09:00 PM IST',
    duration: '100 Mins',
    price: 1199,
    vipPrice: 2999,
    currency: '₹',
    badge: 'Strictly 18+',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    description: 'Late night unfiltered comedy, chess roasts, tech memes, and unexpected VIP stage guests right in the cultural heart of Bandra.',
    tags: ['Bandra Late Night', 'Uncensored', 'Guest Stars'],
    venue: 'Bal Gandharva Rang Mandir, Bandra West'
  }
];

